version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
  kafka:
    image: bitnami/kafka:2.8.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    restart: always
    depends_on:
      - zookeeper
  grafana:
    build: grafana
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana/datasources-ch.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  goflow:
    build:
      context: ../../
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - kafka
    restart: always
    command: 
    - -transport.kafka.brokers=localhost:9092
    - -transport=kafka
    - -transport.kafka.topic=flows
    - -format=pb
    - -format.protobuf.fixedlen=true
    - -metrics.addr=:8081
  db:
    image: yandex/clickhouse-server:21.5.6.6
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d/
      - ../../pb/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
      - ./clickhouse/protocols.csv:/var/lib/clickhouse/user_files/protocols.csv
    depends_on:
      - kafka
